name: Pull Requestプレビュー with GitHub Pages
on: pull_request

jobs:
  deploy:
    name: デプロイ
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Yarnキャッシュディレクトリパス取得
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install
      - run: yarn build
        env:
          BASE_PATH: ./
      - name: Pull Request番号を取得
        id: pull-number
        run: echo "::set-output name=number::$(echo $GITHUB_REF | sed -e 's/refs\/pull\///' -e 's/\/merge//')"
      - run: |
          mkdir -p public/${{ steps.pull-number.outputs.number }}/
          cp -r dist/* public/${{ steps.pull-number.outputs.number }}/
      - uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./public
          publish_branch: gh-pages
          keep_files: true
  comment:
    name: プレビューURLコメント
    runs-on: ubuntu-latest
    if: github.event.action == 'opened'
    steps:
      - uses: actions/github-script@0.2.0
        with:
          github-token: ${{ github.token }}
          script: |
            const { number, pull_request, repository } = context.payload;
            const { name, owner } = repository;
            const { login } = owner;
            const previewUrl = `https://${login}.github.io/${name}/${number}/`;

            github.issues.createComment({
              ...context.issue,
              body: `プレビューは以下のURLでご確認ください。\n\n> ${previewUrl}`
            });

